### ISSUE TITLE
Use `alfred-link`

### ISSUE THREAD

**Issue by SamVerschueren** [vutran/alfred-pokedex#1]
You could use [alfred-link](https://github.com/samverschueren/alfred-link) to actually make your workflow npm installable via `npm` instead of through Packal.

You can even use [alfred-notifier](https://github.com/samverschueren/alfred-notifier) which will show a nice message when there is an update for the workflow.

[alfred-ng2](https://github.com/samverschueren/alfred-ng2) makes use of both these two packages if you want to see an example.

**Comment by vutran** [comment]
Awesome projects you have going on there. This will definitely be super useful.

I've added both `alfred-link` and `alfred-notifier` but can't seem to get linking working correctly. I manually called the `./node_modules/.bin/alfred-link` script and it created the link on my dev copy.

However, installing it globally does creates the symlink but for some reason `info.plist` is missing a `<string>` after the `webaddress` key. This prevents it being read by Alfred. It may be an issue with the `plist` parser but thought I would ask if you know anything beforehand.

**Comment by SamVerschueren** [comment]
That's odd, it should use `homepage` as webaddress value https://github.com/SamVerschueren/alfred-link/blob/master/lib/plist-transform.js#L35. If you can't find it I will look at it later today.

**Comment by SamVerschueren** [comment]
I didn't release the latest version of `alfred-link`. Did a patch release so running `npm install -g alfred-pokedex` now works. The only problem is #2 now. So it doesn't work entirely for this workflow.

Some extra things you can do
1. You could add `npm install -g alfred-pokedex` as the way of installing this package
2. Remove `version`, `description`, `webaddress` and `createdby` from `info.plist` as they are all copied over from `package.json` at install time. I would really recommend doing this, especially for `version` as it will always be out of sync.

**Comment by vutran** [comment]
The latest `alfred-link` patch works.

> Remove version, description, webaddress and createdby from info.plist as they are all copied over from package.json at install time. I would really recommend doing this, especially for version as it will always be out of sync.

Is there a better way we can handle this? Maybe it may make sense to bring this into a build step as well as to retain information for users who may download from [packal.org](http://www.packal.org/)

**Comment by SamVerschueren** [comment]
You can always leave it like it is off course and manage it by hand. For me personally, I'm done with Packal. It takes me more time to release a new workflow on Packal then writing it. That's why @sindresorhus and I decided that it should be done differently. So I'm not interested in creating a pre-build step to be honest. You could always create one yourself if you want. It's not that difficult. You could cherry pick the pieces from `alfred-link`.

**Comment by vutran** [comment]
Thanks. I'm on the same boat as their process takes way too long. If they're download this workflow, it's expected they already have Node/npm installed.

Anyways, going to close this thread for now. I'll maybe work on a packal module if they ever open a publishing API.

**Comment by SamVerschueren** [comment]
I'm going to add a deprecation message on my Packal page for `alfred-ng2`. Don't take the time now to release my new workflows to Packal. It's not even Alfred official.

> I'll maybe work on a packal module if they ever open a publishing API.

Let me know if they do :)
